// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfgxibZ3k62ahbUtCaGNACmcRWRci3iqc',
    appId: '1:129181335985:web:0e696ebedc9f63ffe83d90',
    messagingSenderId: '129181335985',
    projectId: 'subefit-427cc',
    authDomain: 'subefit-427cc.firebaseapp.com',
    storageBucket: 'subefit-427cc.firebasestorage.app',
    measurementId: 'G-D0D61H32MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC2NEdZlc_no1AUW_lROpHSP-9-ipKL60',
    appId: '1:129181335985:android:163bc2ce74682961e83d90',
    messagingSenderId: '129181335985',
    projectId: 'subefit-427cc',
    storageBucket: 'subefit-427cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbAlLJmBAjx8LwFKp1fhJqUeExJOiTzvM',
    appId: '1:129181335985:ios:df0c56619f352fbee83d90',
    messagingSenderId: '129181335985',
    projectId: 'subefit-427cc',
    storageBucket: 'subefit-427cc.firebasestorage.app',
    iosClientId:
        '129181335985-33alfdie99lqihsdp4pro6lt5ebrl9av.apps.googleusercontent.com',
    iosBundleId: 'com.example.subefit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbAlLJmBAjx8LwFKp1fhJqUeExJOiTzvM',
    appId: '1:129181335985:ios:df0c56619f352fbee83d90',
    messagingSenderId: '129181335985',
    projectId: 'subefit-427cc',
    storageBucket: 'subefit-427cc.firebasestorage.app',
    iosClientId:
        '129181335985-33alfdie99lqihsdp4pro6lt5ebrl9av.apps.googleusercontent.com',
    iosBundleId: 'com.example.subefit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfgxibZ3k62ahbUtCaGNACmcRWRci3iqc',
    appId: '1:129181335985:web:ee3d5e9055943aa9e83d90',
    messagingSenderId: '129181335985',
    projectId: 'subefit-427cc',
    authDomain: 'subefit-427cc.firebaseapp.com',
    storageBucket: 'subefit-427cc.firebasestorage.app',
    measurementId: 'G-XNNVZEL708',
  );
}
