import 'exercise_model.dart';

/// Sesiones de entrenamiento predefinidas con múltiples ejercicios y duraciones coherentes.

const cardioSession = DailySession(
  day: 1,
  title: 'Cardio Express (20 min)',
  motivationalQuote: 'Acelera tu corazón y quema calorías',
  exercises: [
    const ExerciseStep(
      name: 'Calentamiento: Marcha en Lugar',
      description: 'Marcha lentamente en lugar, levantando las rodillas',
      duration: Duration(seconds: 60),
      sets: 1,
      points: 5,
      type: 'cardio',
      dificultad: 'principiante',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Saltos Encadenados (Jumping Jacks)',
      description: 'Salta abriendo y cerrando piernas y brazos',
      duration: Duration(seconds: 45),
      sets: 3,
      points: 15,
      type: 'cardio',
      dificultad: 'intermedio',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Burpees',
      description: 'Combinación de sentadilla, flexión y salto',
      duration: Duration(seconds: 30),
      sets: 3,
      points: 20,
      type: 'cardio',
      dificultad: 'avanzado',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Boxeo (Punches)',
      description: 'Realiza golpes directos y combinados en el aire',
      duration: Duration(seconds: 45),
      sets: 2,
      points: 15,
      type: 'cardio',
      dificultad: 'intermedio',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Enfriamiento: Caminar Lentamente',
      description: 'Camina lentamente para bajar la frecuencia cardíaca',
      duration: Duration(seconds: 60),
      sets: 1,
      points: 5,
      type: 'cardio',
      dificultad: 'principiante',
      requiereEquipo: false,
    ),
  ],
);

final fuerzaSession = DailySession(
  day: 2,
  title: 'Fuerza Total (30 min)',
  motivationalQuote: 'Construye músculo, construye fuerza',
  exercises: [
    ExerciseStep(
      name: 'Flexiones (Push-ups)',
      description: 'Baja el cuerpo hasta casi tocar el suelo',
      duration: Duration(seconds: 45),
      sets: 4,
      points: 20,
      type: 'fuerza',
      dificultad: 'intermedio',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Sentadillas (Squats)',
      description: 'Baja las caderas como si fueras a sentarte',
      duration: Duration(seconds: 60),
      sets: 4,
      points: 25,
      type: 'fuerza',
      dificultad: 'intermedio',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Planchas (Planks)',
      description: 'Mantén el cuerpo recto desde cabeza a pies',
      duration: Duration(seconds: 60),
      sets: 3,
      points: 20,
      type: 'fuerza',
      dificultad: 'intermedio',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Dominadas (o Flexiones en Pared)',
      description: 'Sube el cuerpo tirando con los brazos (o apoyado en pared)',
      duration: Duration(seconds: 45),
      sets: 3,
      points: 25,
      type: 'fuerza',
      dificultad: 'avanzado',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Sentadillas Búlgaras',
      description: 'Apoya un pie atrás en una silla y baja',
      duration: Duration(seconds: 45),
      sets: 3,
      points: 20,
      type: 'fuerza',
      dificultad: 'avanzado',
      requiereEquipo: false,
    ),
  ],
);

final flexibilidadSession = DailySession(
  day: 3,
  title: 'Flexibilidad y Movilidad (25 min)',
  motivationalQuote: 'Estira tu cuerpo, libera tu mente',
  exercises: [
    ExerciseStep(
      name: 'Estiramiento Tocarse los Dedos de los Pies',
      description: 'De pie, inclínate hacia adelante sin doblar las rodillas',
      duration: Duration(seconds: 60),
      sets: 2,
      points: 10,
      type: 'movilidad',
      dificultad: 'principiante',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Estiramiento de Mariposa',
      description: 'Sentado, junta las plantas de los pies y presiona las rodillas',
      duration: Duration(seconds: 60),
      sets: 2,
      points: 10,
      type: 'movilidad',
      dificultad: 'principiante',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Pose del Gato-Vaca (Yoga)',
      description: 'Alterna entre arquear y redondear la espalda',
      duration: Duration(seconds: 45),
      sets: 2,
      points: 10,
      type: 'movilidad',
      dificultad: 'principiante',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Rotaciones de Cadera',
      description: 'Haz círculos lentos con las caderas en ambas direcciones',
      duration: Duration(seconds: 60),
      sets: 1,
      points: 10,
      type: 'movilidad',
      dificultad: 'principiante',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Estiramiento de Lunge (Embestida)',
      description: 'Avanza con una pierna manteniendo la otra estirada atrás',
      duration: Duration(seconds: 45),
      sets: 2,
      points: 10,
      type: 'movilidad',
      dificultad: 'intermedio',
      requiereEquipo: false,
    ),
  ],
);

final coreSession = DailySession(
  day: 4,
  title: 'Core y Abdominales (20 min)',
  motivationalQuote: '¡Abdominales marcados, poder potencial!',
  exercises: [
    ExerciseStep(
      name: 'Planchas Frontales',
      description: 'Mantén el cuerpo recto en posición de tabla',
      duration: Duration(seconds: 60),
      sets: 3,
      points: 20,
      type: 'core',
      dificultad: 'intermedio',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Abdominales Tradicionales',
      description: 'Acuéstate y sube el torso sin tirar del cuello',
      duration: Duration(seconds: 45),
      sets: 3,
      points: 15,
      type: 'core',
      dificultad: 'intermedio',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Planchas Laterales',
      description: 'Apóyate en un lado manteniendo el cuerpo recto',
      duration: Duration(seconds: 45),
      sets: 2,
      points: 15,
      type: 'core',
      dificultad: 'intermedio',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Bicicletas (Bicycle Crunches)',
      description: 'Acuéstate y alterna movimientos de pedaleo llevando el codo al opuesto',
      duration: Duration(seconds: 45),
      sets: 3,
      points: 15,
      type: 'core',
      dificultad: 'intermedio',
      requiereEquipo: false,
    ),
  ],
);

final amrapSession = DailySession(
  day: 5,
  title: 'AMRAP: As Many Rounds As Possible (15 min)',
  motivationalQuote: 'Tantas rondas como puedas en 15 minutos',
  exercises: [
    ExerciseStep(
      name: 'Flexiones',
      description: '10 flexiones por ronda',
      duration: Duration(seconds: 30),
      sets: 1,
      reps: '10 reps',
      points: 10,
      type: 'fuerza',
      dificultad: 'intermedio',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Sentadillas',
      description: '15 sentadillas por ronda',
      duration: Duration(seconds: 45),
      sets: 1,
      reps: '15 reps',
      points: 15,
      type: 'fuerza',
      dificultad: 'intermedio',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Burpees',
      description: '5 burpees por ronda',
      duration: Duration(seconds: 30),
      sets: 1,
      reps: '5 reps',
      points: 10,
      type: 'cardio',
      dificultad: 'avanzado',
      requiereEquipo: false,
    ),
  ],
);

final principianteSession = DailySession(
  day: 6,
  title: 'Principiante: Sin Impacto (25 min)',
  motivationalQuote: 'El primer paso es el más importante. ¡Lo estás logrando!',
  exercises: [
    ExerciseStep(
      name: 'Calentamiento: Brazos Circulares',
      description: 'Haz círculos lentos con los brazos en ambas direcciones',
      duration: Duration(seconds: 60),
      sets: 1,
      points: 5,
      type: 'movilidad',
      dificultad: 'principiante',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Flexiones Modificadas (en Rodillas)',
      description: 'Apóyate en las rodillas para hacer flexiones más fáciles',
      duration: Duration(seconds: 45),
      sets: 2,
      points: 10,
      type: 'fuerza',
      dificultad: 'principiante',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Sentadillas Asistidas',
      description: 'Siéntate en una silla y levántate sin usar las manos',
      duration: Duration(seconds: 60),
      sets: 2,
      points: 10,
      type: 'fuerza',
      dificultad: 'principiante',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Planchas en Pared',
      description: 'Apóyate en la pared y mantén el cuerpo alineado',
      duration: Duration(seconds: 45),
      sets: 2,
      points: 10,
      type: 'fuerza',
      dificultad: 'principiante',
      requiereEquipo: false,
    ),
    ExerciseStep(
      name: 'Estiramiento Final',
      description: 'Estira los principales grupos musculares lentamente',
      duration: Duration(seconds: 60),
      sets: 1,
      points: 5,
      type: 'movilidad',
      dificultad: 'principiante',
      requiereEquipo: false,
    ),
  ],
);

/// Lista de todas las sesiones disponibles
final List<DailySession> allSessions = [
  cardioSession,
  fuerzaSession,
  flexibilidadSession,
  coreSession,
  amrapSession,
  principianteSession,
];
